### ISSUE TITLE
Importing gtfs files on the fly

### ISSUE THREAD

**Issue by vandeag** [scrudden/transitime-docker#1]
Hi,

I want to replace existing gtfs with a new one without stopping the app (containers). I assume the import_gtfs.sh file is for that. How do I import those files?

**Comment by scrudden** [comment]
You should log into the container running transiTime using
```
docker exec -it -t transitime-server-instance /bin/bash
```
Within this container you should stop/kill the current core that is running, import the new GTFS and then restart the core.

You can import the new GTFS using  $TRANSITIMECORE/transitime/target/GTFSFileProcessor.jar and use $TRANSITIMECORE/transitime/target/Core.jar to restart core using similar parameters as is in start_transitime.sh. 

Look out for configRev parameter. This should be left out or set to the latest revision.

**Comment by scrudden** [comment]
@vandeag Did this help? Can I close?

**Comment by vandeag** [comment]
@scrudden didn't had time to try it out. Gonna do it this weekend.
