### ISSUE TITLE
Schedule Adherence by Stop missing in webapp?

### ISSUE THREAD

**Issue by qlex** [scrudden/transitime-docker#2]
transitime docker is missing Schedule Adherence by Stop, when compared to standard transitime webapp.
Is it deliverately switched off ?
the correct URL should be like:
http://server:port/web/reports/schAdhByStopParams.jsp?a=agencyid

**Comment by scrudden** [comment]
This depends on the version of transitime you use with this transitime-docker installler. The version used is in the Dockerfile. I am not 100% sure which version has the report you are looking for but I would start with trying the latest version from

https://github.com/Transitime/core

I have been pointing transitime-docker to my own version of transiTime as I have been extending it beyond the version mentioned above.

**Comment by scrudden** [comment]
@qlex This is in the VIA branch now and which will soon become master.

**Comment by scrudden** [comment]
@qlex Can this be closed?

**Comment by qlex** [comment]
Yes, this can be closed

2018-01-20 21:40 GMT+01:00 Sean Óg Crudden <notifications@github.com>:
