### ISSUE TITLE
No GTFS data imported in Transitime

### ISSUE THREAD

**Issue by kalon33** [scrudden/transitime-docker#3]
Using your Docker container with my GTFS file http://ratp.spiralo.net/stif_gtfs_enhanced_rer_latest.zip and GTFS-RT https://stif.spiralo.net/STIF (replacing cap-metro occurrencies by stif and agency id by 1), I could not get any GTFS data in Transitime. When I go in the web interface, agency 1 has no data at all.
Here is, I think, the relevant log:
```
Database is now running.
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
ALTER TABLE
CREATE INDEX
CREATE INDEX
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
CREATE SEQUENCE
CREATE TABLE
CREATE TABLE
Processing configuration file /usr/local/transitime/config/transiTimeConfig.xml
Jul 14, 2017 12:27:48 PM com.mchange.v2.log.MLog <clinit>
INFO: MLog clients using java 1.4+ standard logging.
Jul 14, 2017 12:27:48 PM com.mchange.v2.c3p0.C3P0Registry banner
INFO: Initializing c3p0-0.9.2.1 [built 20-March-2013 10:47:27 +0000; debug? true; trace: 10]
Jul 14, 2017 12:27:48 PM com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource getPoolManager
INFO: Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@7315c25c [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@4d9e0259 [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, debugUnreturnedConnectionStackTraces -> false, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> 1bqq1hf9phxo7ne1ykohf7|5fbe4146, idleConnectionTestPeriod -> 0, initialPoolSize -> 2, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 300, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 20, maxStatements -> 50, maxStatementsPerConnection -> 0, minPoolSize -> 2, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@aa9e732b [ description -> null, driverClass -> null, factoryClassLocation -> null, identityToken -> 1bqq1hf9phxo7ne1ykohf7|4c12331b, jdbcUrl -> jdbc:postgresql://172.17.0.2:5432/stif?connectTimeout=60&socketTimeout=60, properties -> {user=******, password=******} ], preferredTestQuery -> null, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, factoryClassLocation -> null, identityToken -> 1bqq1hf9phxo7ne1ykohf7|26b3fd41, numHelperThreads -> 3 ]
UPDATE 0
```

Could you please help me fixing this? I try to test transitime, but Documentation is pretty low...

**Comment by scrudden** [comment]
There are a large number of agency's in this GTFS file? Is there one in particular you are tying to use transiTime with?

**Comment by kalon33** [comment]
Yes there are. All if possible. if not, 741 (RER) and/or 742 (TRAIN). The GTFS-RT feed will cover them all at some point, using route_id to match with GTFS data. 

Thanks :) 
----- Mail original -----

De: "Sean Óg Crudden" <notifications@github.com> 
À: "scrudden/transitime-docker" <transitime-docker@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 14 Juillet 2017 18:41:26 
Objet: Re: [scrudden/transitime-docker] No GTFS data imported in Transitime (#3) 



There are a large number of agency's in this GTFS file? Is there one in particular you are tying to use transiTime with?

**Comment by scrudden** [comment]
I would try a single instance for a single agency. That is how all the installs I have done work. As far as I know one instance of transTime core will not work for two agencies.

You could use the onebusaway-gtfs-transformer-cli to modify the GTFS file accordingly. Create an GTFS file for each agency and a corresponding transiTime core instance. 

There are options to have a single webapp accessing multiple transiTime cores but that is outside what this docker installer does. This installer does a basic install for a single agency.

**Comment by kalon33** [comment]
@scrudden should I shrink GTFS file or only indicating one of the agency ids in go.sh is sufficient?

**Comment by scrudden** [comment]
@kalon33 I would shrink the GTFS file first. I think it may also work if you indicate a single agency id in go.sh. You could try that after you have tried the shrunk version. I would be interested to know how you get on.

**Comment by kalon33** [comment]
@scrudden I tried with full GTFS and id from one agency, I couldn't get any route in transitime web interface. Is there something particular in standard output when GTFS is processing?

Will try with the shrinked file.

**Comment by scrudden** [comment]
The installer creates two docker machines. One is the database and the other is the core. If you log into the core (transitime-server-instance) as follows you will be able to run the import manually.

```
docker exec -it -t transitime-server-instance /bin/bash
```
Once logged in you can run 
```
./import_gtfs.sh
```
This will write logs to /usr/local/transitime/logs/ . The file you are looking for is core.log. It should have details about any issues with the GTFS import.

**Comment by scrudden** [comment]
@kalon33 Can I close this issue?

**Comment by kalon33** [comment]
Dear Sean, I finally gave up using Transitime, as my feed has multiple agencies and it seems to me a pain to deal with that. So I didn't fixed my problem, but except if there's a fast, easy solution, you can close this. 

----- Mail original -----

De: "Sean Óg Crudden" <notifications@github.com> 
À: "TheTransitClock/transitclockDocker" <transitclockDocker@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Mention" <mention@noreply.github.com> 
Envoyé: Mardi 12 Décembre 2017 19:58:42 
Objet: Re: [TheTransitClock/transitclockDocker] No GTFS data imported in Transitime (#3) 



@kalon33 Can I close this issue?

**Comment by scrudden** [comment]
As per kalon33 comment above.
