### ISSUE TITLE
Unavailable tomcat version

### ISSUE THREAD

**Issue by changtung** [scrudden/transitime-docker#4]
In DockerFile there is unavailable tomcat version beeing downloaded. 
8.0.36
This version is unavailable and download is not possible and it generated other errors. 
I changed version to 8.0.46 and commented out pgp public key check and it works fine then.

**Comment by scrudden** [comment]
I think it will be better to change the URL in the docker file to point at the archive. 

http://archive.apache.org/dist/tomcat/

The tomcat versions remain there.

**Comment by scrudden** [comment]
Fixed. Using archive.
